### ISSUE TITLE
an interface method must be abstract

### ISSUE THREAD

**Issue by jose** [jboss-javassist/javassist#104]
Hi,

Since Java-8 that an _Interface_ can have _default_ and _static_ methods. however, I'm trying to add a static method to an interface using javassist, and it doesn't seem to be allowed. here the error message:
```
javassist.CannotCompileException: an interface method must be abstract:
	at javassist.CtClassType.addMethod(CtClassType.java:1379)
```

My system:
OpenJDK 64-Bit 1.8.0_91
javassist 3.20.0-GA

**Comment by chibash** [comment]
Thanks.  I fixed it and committed it.
