### ISSUE TITLE
java.io.IOException: invalid constant type: 15 at 1620

### ISSUE THREAD

**Issue by naveen12** [jboss-javassist/javassist#115]
Facing issue when i used Javassist.jar 11/06/2012 modified date, 65 KB file displaying issue like java.io.IOException: invalid constant type: 15 at 1620
i changed different javassist files but also same issue 

and using Javasnoop  tool to test thick client application. faced this exception

**Comment by chibash** [comment]
Please post a test program reproducing this bug.

**Comment by naveen12** [comment]
Hey chibash,
This issue was resolved with javassist_3.21.0-GA jar file
thanks for your support and development
