### ISSUE TITLE
Checksum problem for 3.18.1-GA on Maven Central

### ISSUE THREAD

**Issue by r0man** [jboss-javassist/javassist#120]
Hello,

I think there's a problem with the checksum for the `3.18.1-GA` artifact on Maven Central.

```
Could not transfer artifact org.javassist:javassist:jar:3.18.1-GA from/to central (https://repo1.maven.org/maven2/):
Checksum validation failed, expected d9a09f7732226af26bf99f19e2cffe0ae219db5b but is 1153878fa3db0c164318521e8e77106f9099f4e5
```
Could you please take a look at this?

Thanks, Roman

**Comment by potetm** [comment]
A touch more information:

It looks to just be modified dates that somehow changed.

```
/tmp> diff -r old-javassist/ new-javassist/
diff -r old-javassist/META-INF/MANIFEST.MF new-javassist/META-INF/MANIFEST.MF
33c33
< Bnd-LastModified: 1377882079822
---
> Bnd-LastModified: 1377888052262
diff -r old-javassist/META-INF/maven/org.javassist/javassist/pom.properties new-javassist/META-INF/maven/org.javassist/javassist/pom.properties
2c2
< #Fri Aug 30 13:01:19 EDT 2013
---
> #Fri Aug 30 14:40:52 EDT 2013
```

**Comment by akjetma** [comment]
We're having this issue as well!

**Comment by akjetma** [comment]
This seems to be working for us now. Guessing this was an issue with the maven central repo?

**Comment by r0man** [comment]
It works for me as well again. Thanks to everyone looking into this.

**Comment by scottmarlow** [comment]
This may of been because I didn't publish my key when I renewed it.  The [working-with-pgp-signatures](http://central.sonatype.org/pages/working-with-pgp-signatures.html) link mentions that "gpg2 --keyserver hkp://pool.sks-keyservers.net --send-keys ..." must be used to distribute the key to a public server.
