### ISSUE TITLE
how to use another class's method?

### ISSUE THREAD

**Issue by Windson1806** [jboss-javassist/javassist#124]
hi,
i want to invoke another class's(class B) static method in the code i inject into the class which i modified(class A).
but there is a problem with that,the JVM will crash because of the B class cann't find.
in console ,it says 
java.lang.NoClassDefFoundError: path/to/class/B
the code i use to inject,like this:
"{System.out.println(path.to.class.B.method());}"
i googled for a long time till now.
can anyone help me with this??
TKS.

**Comment by MrXRain** [comment]
hi,freind. How to solve this problem

**Comment by windsonR** [comment]
I don't remember.Its 6 years...
