### ISSUE TITLE
Javaassist has something wrong when insert code in particular situation

### ISSUE THREAD

**Issue by mivanzhang** [jboss-javassist/javassist#136]
I want to insert code using insertbefore() method, it works perfectly in most cases, but when I insert code into the classes generated by AspectJ whose methods have Object Array as parameters ,things goes wrong .
here is the code generated 

```java

       Class  clsArr = Class.forName("[Ljava/lang/Object;");
       
```
Class.forName("[Ljava/lang/Object;"); takes wrong parameters,

you can reproduce this in our demo https://github.com/Meituan-Dianping/Robust/tree/newFeature

you should change Robust version to 0.3.8, and you can see the code in class MainActivity$AjcClosure1, evil is there.

thank you for your reading ,Javaassist is a wondful tools, wish your reply

**Comment by chibash** [comment]
I cannot see what's wrong but insertBefore() may fail if the bytecode is not generated by javac (and hence it is far different typical bytecode generated from Java source.)
