### ISSUE TITLE
Cannot change visibility of Nested classes

### ISSUE THREAD

**Issue by paulo-raca** [jboss-javassist/javassist#139]
I'm trying to make every class in a package public.

Basically, for every CtClass:
```ctClass.setModifiers( Modifier.setPublic(ctClass.getModifiers()));```

This works fine for upper-level classes, but seems to have no effect on Subclasses.

(A few other manipulations work on subclasses just fine)

**Comment by chibash** [comment]
Did you call setModifiers on every subclass one by one? 
You have to do so.

**Comment by paulo-raca** [comment]
Yes.
My code basically lists every .class file in the classpath, removes the `.class` suffix and replaces `$` with `.` to get a list of every class it needs to check.
It will process each of these classes independently, ignoring whenever it's a subclass or not.
It processes `Outer` and `Outer$Inner`, but the visibility is only updated on `Outer`.

I also apply some other changes using `ctMethod.instrument()`, and these work fine both for Outer and Inner classes.

**Comment by paulo-raca** [comment]
I've been investigating it a little, and I guess that since "outer" classes can only be public or package-visible, those are the only values mapped on `CtClass.getModifiers()`.

If the class _should by_ `private`, the resulting modifier actually says `PUBLIC`.
If the class _should by_ `protected`, the resulting modifier actually indicates `"PACKAGE-VISIBLE"`.

I've also tested a few other modifiers (static, final, abstract) and these seem to work fine.

[Here is a small gist with the code to reproduce it](https://gist.github.com/paulo-raca/42ea00bbcda4c14d345c43de6c35bb84)

**Comment by paulo-raca** [comment]
Another weird observation.

I'm now using `ctClass.setModifiers( Modifier.setPublic(ctClass.getModifiers()));` to update the classes.

Javassist and `javap` both see the modified classes as public.

AndroidStudio and the [Fernflower decompiler](https://github.com/JetBrains/intellij-community/tree/master/plugins/java-decompiler/engine) do not, and show the unmodified visibility.

The only thing I can think of is that the access modifier is being stored in redundant places.

**Comment by chibash** [comment]
Ah, yes, you also have to update the InnerClasses attribute of the inner classes.

**Comment by paulo-raca** [comment]
How do I do that?

**Comment by chibash** [comment]
javassist.bytecode.InnerClassesAttribute#setAccessFlags

**Comment by paulo-raca** [comment]
Thank you!

Would it make sense to use InnerClassesAttribute automatically on `CtClass.getModifiers()` / `CtClass.setModifiers()` ?

**Comment by chibash** [comment]
I've modified CtClass.setModifiers() to do so.

**Comment by paulo-raca** [comment]
Thanks a lot!
