### ISSUE TITLE
Is it possible to use Javassist to remove bytecode instruction?

### ISSUE THREAD

**Issue by lzl144** [jboss-javassist/javassist#140]
I am wondering is it possible to use javassist to remove bytecode instructions in java class? I have read the online manual, but I did not find clues from it...  

Thank you！

**Comment by nickl-** [comment]
Could you elaborate or explain your use case please?

How would you identify the bit code to be removed?

**Comment by chibash** [comment]
The higher-level API (= javassist.*) does not allow you to delete bytecode since deleting is dangerous.
However, if you use the lower-level API (= javassist.bytecode.*), yes, you can do it at your own risk.
