### ISSUE TITLE
Javassist generate new class with the major version 52, which cannot be compatible with JDK7

### ISSUE THREAD

**Issue by mivanzhang** [jboss-javassist/javassist#141]
which factor decide the major version in new-genreated class.like follow

```java
classPool.makeClass()
```

 version is compile 'org.javassist:javassist:3.20.0-GA'

**Comment by chibash** [comment]
the value of javassist.bytecode.ClassFile#MAJOR_VERSION

**Comment by mivanzhang** [comment]
I use this classPool.makeClass() method to create new class ,but in different project genreat classes are different,  I saw the source code in ClassFile, I found the default  major version is 51, but why I create a class with the  major version 52?

**Comment by chibash** [comment]
Do ctClass.getClassFile().setMajorVersion(ClassFile.JAVA_7) and save it.

**Comment by mivanzhang** [comment]
thanks

**Comment by mivanzhang** [comment]
We found Javassit with version 3.21.0-GA ```classPool.makeClass()``` create class with the MajorVersion is 52(Java 8),but when I use 3.20.0-GA, create class with the MajorVersion is 51(Java 7), what has changed between the two version, what`s the difference @chibash

**Comment by chibash** [comment]
because 3.21.0-GA does not understand Java 8 or 9.
