### ISSUE TITLE
Wrong modifiers returned for nested classes

### ISSUE THREAD

**Issue by pietrobraione** [jboss-javassist/javassist#152]
I assume that the method javassist.CtClass.getModifiers() should return identical values as if the class were loaded and java.lang.Class.getModifiers() were invoked. In this case the two methods differ when Javassist is fed by the classes:

    package foo;
    public class Foo {
        protected class Baz { }
        private class Gee { }
    }

The current implementation of javassist.CtClassType.getModifiers() returns 1 (AccessFlag.PUBLIC) for foo.Foo$Baz and 0 (meaning package visibility) for foo.Foo$Gee, when java.lang.Class.getModifiers() returns 4 (Modifier.PROTECTED) and 2 (Modifier.PRIVATE) respectively.

A quick read of javassist.CtClassType.getModifiers() source code reveals that only AccessFlag.STATIC is checked of the inner access flags, so I reckon a possible fix could be something like:

    public int getModifiers() {
        ClassFile cf = getClassFile2();
        int acc = cf.getAccessFlags();
        acc = AccessFlag.clear(acc, AccessFlag.SUPER);
        int inner = cf.getInnerAccessFlags();
        if (inner != -1) {
            if ((inner & AccessFlag.STATIC) != 0) {
                acc |= AccessFlag.STATIC;
            }
            if ((inner & AccessFlag.PUBLIC) != 0) {
                //seems that public nested classes already have the PUBLIC modifier set
                //but we are paranoid and we set it again
                acc |= AccessFlag.PUBLIC;
            } else if ((inner & AccessFlag.PROTECTED) != 0) {
                acc &= ~AccessFlag.PUBLIC //clear the PUBLIC modifier in case it is set
                acc |= AccessFlag.PROTECTED;
            } else if ((inner & AccessFlag.PRIVATE) != 0) {
                acc &= ~AccessFlag.PUBLIC //clear the PUBLIC modifier in case it is set
                acc |= AccessFlag.PRIVATE;
            } else { //package visibility
                acc &= ~AccessFlag.PUBLIC //clear the PUBLIC modifier in case it is set
            }
        }

        return AccessFlag.toModifier(acc);
    }

Note that the above code is untested!

**Comment by nickl-** [comment]
Issue can be closed pending PR #167
