### ISSUE TITLE
About the combination of classes

### ISSUE THREAD

**Issue by SilenceCarrot** [jboss-javassist/javassist#161]
Hello, I have a question want to ask for you. Hope that the great god to give help, thanks.

Describe my question:
I want to achieve the following results, but the creation of examples, the console will be an error.
`
Class A {
    String name;

    public void setName() {...};
    public void getName(){...};
}

Class B {
  A a;
}

main(...) {
    B b = new B();
}
`

See my code.
First, define a base class:
`
package carrot.hu.mockdubbo.service.bean;

import java.io.Serializable;

public class TemplateBean implements Serializable {
}
`

In the second part, we implement the combination of classes:
`
public void test2() {
        try {
            ClassPool classPool = ClassPool.getDefault();
            CtClass ctClass1 = classPool.get("carrot.hu.mockdubbo.service.bean.TemplateBean");
            ctClass1.setName("carrot.hu.mockdubbo.service.bean.A");

            CtField FA1 = new CtField(classPool.get("java.lang.String"), "FA1", ctClass1);
            FA1.setModifiers(Modifier.PUBLIC);
            ctClass1.addField(FA1, CtField.Initializer.constant("wei.hu"));

            CtField FA2 = new CtField(classPool.get("int"), "FA2", ctClass1);
            FA2.setModifiers(Modifier.PUBLIC);
            ctClass1.addField(FA2, CtField.Initializer.constant("24"));

            ctClass1.addMethod(CtNewMethod.setter("setFA1", FA1));
            ctClass1.addMethod(CtNewMethod.getter("getFA1", FA1));

            ctClass1.addMethod(CtNewMethod.setter("setFA2", FA2));
            ctClass1.addMethod(CtNewMethod.getter("getFA2", FA2));

            CtClass ctClass2 = classPool.get("carrot.hu.mockdubbo.service.bean.TemplateBean");
            ctClass2.setName("carrot.hu.mockdubbo.service.bean.B");

            CtField FB1 = new CtField(classPool.get("carrot.hu.mockdubbo.service.bean.A"), "FA", ctClass2);
            FB1.setModifiers(Modifier.PUBLIC);
            ctClass2.addField(FB1, CtField.Initializer.byNew(ctClass1));

            ctClass2.addMethod(CtNewMethod.setter("setFB1", FB1));
            ctClass2.addMethod(CtNewMethod.getter("getFB1", FB1));

        } catch (NotFoundException e) {
            e.printStackTrace();
        } catch (CannotCompileException e) {
            e.printStackTrace();
        } 
    }
`

The third step, when creating an instance of ctClass 2 will be an error：
`
            Class<?> clazz = ctClass2.toClass();
            Object object = clazz.newInstance();
`

ERROR：
`
Exception in thread "main" java.lang.NoClassDefFoundError: carrot/hu/mockdubbo/service/bean/A
	at carrot.hu.mockdubbo.service.bean.B.<init>(TemplateBean.java:5)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at carrot.hu.mockdubbo.service.bean.CreateClass.test2(CreateClass.java:89)
	at carrot.hu.mockdubbo.service.bean.CreateClass.main(CreateClass.java:110)
Caused by: java.lang.ClassNotFoundException: carrot.hu.mockdubbo.service.bean.A
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
`

Do not know where the problem.
Hope that the gods pointing mountains. thanks.

**Comment by chibash** [comment]
Have you loaded CtClass1 first?  The error message can be read as A is not found.

**Comment by SilenceCarrot** [comment]
According to my writing, I used ctClass 1 on the ctClass 2 members to initialize, ctClass1 has been obtained from the classPool. Why is not it loaded? @chibash

**Comment by chibash** [comment]
ClassPool is not part of the JVM.  It is just a user-level hash table.  It's not relevant to class loaders.

Did you explicitly invoke ctClass1.toClass()?  You must tell your JVM to load it.  Without this, ctClass1 is just a byte array from the viewpoint of the JVM.

**Comment by SilenceCarrot** [comment]
Forgive me stupid. I follow your instructions, before ctClass2 instantiation, the first load ctClass1, but still reported ERROR, I do not understand, again trouble you advise.

For convenience, I simplified the program to write a demo, as follows:

`
public static void test3() {
        try {
            ClassPool classPool = ClassPool.getDefault();
            CtClass ctClass1 = classPool.makeClass("carrot.hu.A");

            CtField fieldName = new CtField(classPool.get("java.lang.String"), "FA1", ctClass1);
            fieldName.setModifiers(Modifier.PUBLIC);
            ctClass1.addField(fieldName, CtField.Initializer.constant("wei.hu"));

            ctClass1.addMethod(CtNewMethod.setter("setFA1", fieldName));
            ctClass1.addMethod(CtNewMethod.getter("getFA1", fieldName));

            ctClass1.toClass();

            CtClass ctClass2 = classPool.makeClass("carrot.hu.B");

            CtField fieldA = new CtField(classPool.get("carrot.hu.B"), "fieldA", ctClass2);
            fieldA.setModifiers(Modifier.PUBLIC);
            ctClass2.addField(fieldA, CtField.Initializer.byNew(ctClass1));

            Class<?> clazz = ctClass2.toClass();
            Object object = clazz.newInstance();


        } catch (CannotCompileException e) {
            e.printStackTrace();
        } catch (NotFoundException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        }

    }
`

ERROR:
`
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    carrot/hu/B.<init>()V @13: putfield
  Reason:
    Type 'carrot/hu/A' (current frame, stack[1]) is not assignable to 'carrot/hu/B'
  Current Frame:
    bci: @13
    flags: { }
    locals: { 'carrot/hu/B' }
    stack: { 'carrot/hu/B', 'carrot/hu/A' }
  Bytecode:
    0x0000000: 2ab7 000c 2abb 000f 592a b700 12b5 0014
    0x0000010: b1                                     

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at cn.fraudmetrix.mockdubbo.service.bean.CreateClass.test3(CreateClass.java:127)
	at cn.fraudmetrix.mockdubbo.service.bean.CreateClass.main(CreateClass.java:145)
`

Thank you again in advance, please give me some guidance.

**Comment by chibash** [comment]
CtField fieldA = new CtField(classPool.get("carrot.hu.B"), "fieldA", ctClass2);
fieldA.setModifiers(Modifier.PUBLIC);
ctClass2.addField(fieldA, CtField.Initializer.byNew(ctClass1));

According to this code, fieldA seems to have type B (= ctClass2) but its initial value is an instance
of A (= ctClass1).  This is not valid Java code.

**Comment by SilenceCarrot** [comment]
Hello, ask you again.

CtField fieldA = new CtField(classPool.get("carrot.hu.B"), "fieldA", ctClass2);
fieldA.setModifiers(Modifier.PUBLIC);
ctClass2.addField(fieldA, CtField.Initializer.byNew(ctClass1));

I decompile the class B.

`
package carrot.hu;
import java.io.Serializable;

public class B implements Serializable {
    public A FA = new A(this);

    public B() {
    }

    public void setFB1(A var1) {
        this.FA = var1;
    }

    public A getFB1() {
        return this.FA;
    }
}
`

But found that the member variable FA is so initialized.
public A FA = new A(this);

This seems to be a problem when constructing an object A. But where is my javassist code out of the problem? Cause there is a this here.

**Comment by nickl-** [comment]
This seems like a new question, if the original question was answered, please confirm and allow the issue to be closed. If you have additional questions you should create a new Issue.

For passing `this`  to the constructor of new object instance, which requires `this`, as the value for a `CtField`, have you tried:

```
CtClass cc = ClassPool.getDefault().get("B");
CtField f = CtField.make("public A FA = new A(this);", cc);
cc.addField(f);
```

As per the tutorial... 4.3 Adding a new field.

**Comment by nickl-** [comment]
@SilenceCarrot see nickl-/javassist@3e64cfb for test case modification with CtField.make referencing `this`

**Comment by SilenceCarrot** [comment]
nice，thank you very much.
but there have a new question.  
eg: 
`
class B {
   String str;
}

class A {
    B b;
}
`
like this, now I can do it. However, see this:
`
 class B<T> {
    T val;
}
`
I do not know whether javassist now supports generics. How to achieve class B.
