### ISSUE TITLE
Estimated release date for 3.19.0-GA

### ISSUE THREAD

**Issue by megazord** [jboss-javassist/javassist#17]
When will this version be released? Mainly because it fix #13.

**Comment by tazmaniax** [comment]
@chibash Any update on this? thx

**Comment by chibash** [comment]
I've tagged 3.19.0-GA release.  Sorry for the late release.

**Comment by tazmaniax** [comment]
@chibash thx

**Comment by mpet** [comment]
When is the next release scheduled for java-assist? (Javassist 3.21.0-GA release)?

//mikael

**Comment by chibash** [comment]
The last release was June.  So the next will be November or December unless someone has a strong demand for earlier release.
