### ISSUE TITLE
How to supports generics.

### ISSUE THREAD

**Issue by SilenceCarrot** [jboss-javassist/javassist#172]
there have a new question.  
eg: 
`
class B {
   String str;
}

class A {
    B b;
}
`
like this, now I can do it. However, see this:

 class B < T > {
    T val;
}

I do not know whether javassist now supports generics. How to achieve class B.

**Comment by chibash** [comment]
At bytecode level, type parameters like T are erased.  So,

class B {
  Object val;
}

is what you want.  You have to manually insert type casts where they are needed.

**Comment by SilenceCarrot** [comment]
OK，OK，I understand. thank you very much.
