### ISSUE TITLE
Different Instruction ByteCode between javassist output and the real byteCode (with javap)

### ISSUE THREAD

**Issue by Jnsll** [jboss-javassist/javassist#173]
## Environment
Java : 8
Javassist : 3.12.1

## Context
We were trying to modify the bytecode of the project Commons Math https://github.com/apache/commons-math  . 
When looping  through the code thanks to a CodeIterator object, we could observe an unexpected behaviour. The instruction bytecode returned by Javassist was different from the bytecode found when performing the command javap.

The issue was raised with the following method from the Common Math project :
class : org.apache.commons.math4.stat.inference.KolmogorovSmirnovTest
method : pelzGood(double, int)

We can see (cf section Output) that the index number 71 is 'ldc' with Javassist whereas it is 'ldc_w' with javap. Thus, there is a shift in the following instructions and we encounter a problem when we want to modify the bytecode of those instructions.

## Code

```java
InstructionPrinter printer = new InstructionPrinter(System.out);
CtClass ctClass = pool.get("org.apache.commons.math4.stat.inference.KolmogorovSmirnovTest");
printer.print(ctClass.getDeclaredMethod("pelzGood"));
```

### output with javassist : 
```
0: iload_3
1: i2d
2: invokestatic #53 = Method org.apache.commons.math4.util.FastMath.sqrt((D)D)
5: dstore 4
7: dload_1
8: dload 4
10: dmul
11: dstore 6
13: dload_1
14: dload_1
15: dmul
16: iload_3
17: i2d
18: dmul
19: dstore 8
21: dload 8
23: dload 8
25: dmul
26: dstore 10
28: dload 10
30: dload 8
32: dmul
33: dstore 12
35: dload 10
37: dload 10
39: dmul
40: dstore 14
42: dconst_0
43: dstore 16
45: dconst_0
46: dstore 18
48: dconst_0
49: dstore 20
51: dconst_0
52: dstore 22
54: ldc2_w #55 = int 9.869604401089358
57: ldc2_w #57 = int 8.0
60: dload 8
62: dmul
63: ddiv
64: dstore 24
66: iconst_1
67: istore 26
69: iload 26
**71: ldc #59 = int 100000**
73: if_icmpge 127
76: iconst_2
77: iload 26
79: imul
80: iconst_1
81: isub
82: i2d
83: dstore 22
85: dload 24
87: dneg
88: dload 22
90: dmul
91: dload 22
93: dmul

    ...

```

###  output with "javap -c KolmogorovSmirnovTest.class"
```
      0: iload_3
      1: i2d
      2: invokestatic  #306                // Method org/apache/commons/math4/util/FastMath.sqrt:(D)D
      5: dstore        4
      7: dload_1
      8: dload         4
     10: dmul
     11: dstore        6
     13: dload_1
     14: dload_1
     15: dmul
     16: iload_3
     17: i2d
     18: dmul
     19: dstore        8
     21: dload         8
     23: dload         8
     25: dmul
     26: dstore        10
     28: dload         10
     30: dload         8
     32: dmul
     33: dstore        12
     35: dload         10
     37: dload         10
     39: dmul
     40: dstore        14
     42: dconst_0
     43: dstore        16
     45: dconst_0
     46: dstore        18
     48: dconst_0
     49: dstore        20
     51: dconst_0
     52: dstore        22
     54: ldc2_w        #307                // double 9.869604401089358d
     57: ldc2_w        #309                // double 8.0d
     60: dload         8
     62: dmul
     63: ddiv
     64: dstore        24
     66: iconst_1
     67: istore        26
     69: iload         26
     **71: ldc_w         #311                // int 100000**
     74: if_icmpge     128
     77: iconst_2
     78: iload         26
     80: imul
     81: iconst_1
     82: isub
     83: i2d
     84: dstore        22
     86: dload         24
     88: dneg
     89: dload         22
     91: dmul
     92: dload         22
     94: dmul
```

**Comment by chibash** [comment]
The outputs look OK.  ldc is used for an 8bit operand (index 59) and ldc_w is for 16bit operand (index 311).

**Comment by Jnsll** [comment]
In our project, we proceed with 2 steps : 
- in a method, we retrieve the indexes for which the bytecode correspond to "imul" (for example, the 79th index from the peIzGood method according to the Javassist output)
- We replace the instruction of the retrieved indexes ("imul") by another one (for example "idiv") : writeByte("idiv", 79)

Because of the shift caused by the 'ldc_w' instruction, we are told that the 79th index is not "imul" but "iload" during the replacement.

We don't understand why there is a difference (8-bit with Javassist and 16-bit with Javap).

**Comment by chibash** [comment]
Please read Chap. 4.4 and 6.5 of the JVM specifications.
Your two step algorithm might be unfortunately too naive to correctly manipulate bytecode.

**Comment by Jnsll** [comment]
Thank you for your feedback. We've found our mistake elsewhere.
