### ISSUE TITLE
Jar -uvf throws io exception after modifying class file

### ISSUE THREAD

**Issue by Zhang-Xianglong** [jboss-javassist/javassist#200]
I used javassist to modify a class in the jar file and output it to a temporary folder. Then use Process to run jar-uvf to update the modified class file to the jar file, but the io exception is generated, it seems that javassist open jar file is not released, may I ask why? How to solve?

**Comment by Zhang-Xianglong** [comment]
Occurs under Windows, normal under Linux.

**Comment by chibash** [comment]
I suppose that this problem has been fixed in HEAD.

**Comment by Zhang-Xianglong** [comment]
Thanks a lot :-)
