### ISSUE TITLE
static final field which hasn't got a literal initializer is not treated as constant

### ISSUE THREAD

**Issue by seelikes** [jboss-javassist/javassist#203]
but it do exist in constantPool.

i.e. public static final boolean DEBUG = Boolean.parseBoolean("true")

**Comment by chibash** [comment]
Are you using CtClass#addField(CtField, CtField.Initializer)?
Does it have a bug?

**Comment by seelikes** [comment]
@chibash not exactly. i am using CtField#getConstantValue() to get DEBUG's value, but i got null. i do think it is constant since it has static and final modifiers. i check the test in JvstTest2#testConstField, the integer field which has the same behavior was asserted as null,  it seems this was designed.  i think i am confused, since it is static and final modifiers  making a field constant, why is it failing when field has a expression initializer? further more, the code i cloned from my fork can not work, the root pom has gpg.passphrase and gpg.useAgent which  do not exist in any file belonging to this project.

**Comment by chibash** [comment]
It depends on the compiler whether DEBUG's value is really a constant.
Since your code calls Boolean.parseBoolean("true"), I suppose that the compiler determined
parseBoolean() had to be invoked at runtime and thus DEBUG's value is not a constant
although DEBUG is static and final.

**Comment by seelikes** [comment]
@chibash is there any chance that i got the initializer Boolean.parseBoolean("true") with javassist?

**Comment by seelikes** [comment]
@chibash thank very much, i think i can close this issue.
