### ISSUE TITLE
ConcurrentModificationException in 3.23.1 GA

### ISSUE THREAD

**Issue by WarrenCooper-sag** [jboss-javassist/javassist#224]
Powermock test cases are failing after upgrading Javassist from 3.22.0 to 3.23.1.
The issue is reported to Powermock site.
https://github.com/powermock/powermock/issues/924

Switching the two 'instrument' methods back to get instead of Iterate proved successful for me.
See attached. ( Sorry, I can create a pull request if desired once granted access. )

[CtClassType.java.zip](https://github.com/jboss-javassist/javassist/files/2448003/CtClassType.java.zip)

-thanks

**Comment by chibash** [comment]
Please try javassist.jar in https://github.com/jboss-javassist/javassist/releases/tag/rel_3_24_0_rc

**Comment by WarrenCooper-sag** [comment]
3.24.0_rc pases all my tests.

Thanks for the quick turnaround!
