### ISSUE TITLE
The difference between ClassPool.insertClassPath() and ClassPool.appendClassPath()

### ISSUE THREAD

**Issue by lygoing** [jboss-javassist/javassist#225]
@chibash hi.
Such as the title.
I don't understand the difference between them, ask for advice.

Thanks.

**Comment by chibash** [comment]
The difference is the position where the class path is added in the class-path list.  #insertCP() puts at the first element.  #appendCP() puts at the end.

Please see [this page](http://www.javassist.org/html/javassist/ClassPool.html#insertClassPath-javassist.ClassPath-).

**Comment by lygoing** [comment]
> The difference is the position where the class path is added in the class-path list. #insertCP() puts at the first element. #appendCP() puts at the end.
> 
> Please see [this page](http://www.javassist.org/html/javassist/ClassPool.html#insertClassPath-javassist.ClassPath-).

Oh, thank you very much for your time.
