### ISSUE TITLE
Compatibility down to JDK 8/7 ?

### ISSUE THREAD

**Issue by skybber** [jboss-javassist/javassist#226]
Hi, is the next 3.24.0 version supposed to support JDK8? Currently compilation fails with:
`
[ERROR] /home/lada/workspaces/workspace-ha/javassist/src/main/javassist/util/proxy/DefineClassHelper.java:[295,66] cannot find symbol
[ERROR]   symbol:   method getModule()
`

**Comment by NingZhang-Ericsson** [comment]
Please check pom file:
[pom.xml](https://github.com/jboss-javassist/javassist/blob/master/pom.xml)
```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          <testSource>11</testSource>
          <testTarget>11</testTarget>
          <testCompilerArgument>-parameters</testCompilerArgument>
        </configuration>
</plugin>
```
It could work with JDK8 not 7 anymore.

If you want build it locally, JAVA_HOME should be Java 11.

**Comment by skybber** [comment]
Thanks, we are using embedded javassist in HotswapAgent project so we will try switch build to j11.

**Comment by JCgH4164838Gh792C124B5** [comment]
Hello @NingZhang-Ericsson .

With Javassist 3.23 -> 3.24 the source/target levels for the compile changed from 1.6 -> 1.8.  Is there anything in 3.24 (and later) that depends on JDK8 or would it be possible to change the source/target level for the compile to 1.7 (to retain compile compatibility with JDK7 for the time being) ?

**Comment by chibash** [comment]
javassist.util.proxy includes the code for supporting Java 11 etc.  So that code would not be
compiled by the JDK7 compiler since it includes Java 11 methods.  Except that, the target
could be JDK7.

**Comment by JCgH4164838Gh792C124B5** [comment]
Hello @chibash .
Thanks for clarifying that. 

Since the previous source/target was 1.6 for Javassist 3.23, maybe 3.25+ could revert to source/target 1.7 for a little while longer - since it is a smaller incremental change in platform support for Javassist ?  

That way Javassist could support running on JDK 7 for a little while longer - at least until there's source code changes that require moving to a newer JDK source/target (such as 1.8) ?
