### ISSUE TITLE
Insert a bytecode instruction before an `else if` statement

### ISSUE THREAD

**Issue by jose** [jboss-javassist/javassist#233]
Hi,

I usually use the following piece of code to instrument each statement in a Java program:
```java
...
Bytecode byteCode = ...
codeIterator.insert(pos, byteCode.get());
...
```
Basically it inserts the given bytecode sequence **before** the instruction at the given index `pos`. However, where is the bytecode sequence inserted for an `else if` statement?
```java
       ...
11.  boolean ret = false;
12.  if (i < 50) {
13.    ret = true;
14.  } else if (i > 50 && i < 100) {
15.    ret = false;
16.  }
       ...
```
Is it inserted in line number 14 right after the `}` that closes the `if` condition in line 12? Is that allowed by the JVM? If not, where is it inserted?

--
Best,
Jose

**Comment by chibash** [comment]
The Java byte code is like an assembly language.
So it does not have a if-else statement.  Only branch and goto instructions.
