### ISSUE TITLE
Inject bytecode into CloseableHttpClient(apache HttpClients)

### ISSUE THREAD

**Issue by ab91963931372** [jboss-javassist/javassist#238]
These days I am doing a mock function of a third-party method, in which the bytecode of the third-party methods (such as redis read, mysql read, http call) is modified to meet my needs. However, I found that under the premise that I modified the OpenableHttpClient's execute method, it did not execute the content I added when I actually executed it (maybe you can try it), then I debugged it. The CloseableHttpClient object is actually InternalHttpClient Object, but the latter did not rewrite the execute method, I also tried to simulate this situation with a Demo, but it can be successful, I printed the method name of the object and found that it contains the method I added. I don't know why it did not work in OpenableHttpClient.

**Comment by NingZhang-Ericsson** [comment]
It is hard to troubleshoot without code. Suggest you simplify the code to make it more like unit test. 
That will help troubleshooting.
