### ISSUE TITLE
not found exception for BigDecimal divide method

### ISSUE THREAD

**Issue by horakhsh** [jboss-javassist/javassist#261]
I have an expression that in which a BigDecimal divide method with the following signature is used : 
BigDecimal 	divide​(BigDecimal divisor)
In compiling that exp I get the following exception : 
compile error: divide​(java.math.BigDecimal) not found in java.math.BigDecimal 
what is the problem with divide method? 
I am using jdk 10 with Javassist 3.24/3.25

**Comment by chibash** [comment]
Can you show us test code for reproducing this bug?

**Comment by horakhsh** [comment]
Hi chibash 
 thanks a lot for your response 
  I found the problem. 
there was some non-viewing zero-length chars along with "devide" method name in my source code
