### ISSUE TITLE
Is v3.23 the last jdk6 supported version?

### ISSUE THREAD

**Issue by wu-sheng** [jboss-javassist/javassist#268]
Hi

I noticed from 3.24, the root pom.xml sets compile/target level to JDK 1.7. So do all 1.6 supports stay in 3.32 only? Also, I notice, 3.23.2-GA has released 3 months ago.

Could you share the plan for JDK 1.6?

**Comment by NingZhang-e** [comment]
It can still support creating dynamic classes for Java6 class after 3.24.  But it requires your JRE is above 7.
I agree with the project should NOT stick to Java6 anymore since it is too old. Stick to Java6 means new Java features (source) can not be used.
I do not think JRE6 should be supported anymore but that requires @chibash to confirm.

**Comment by wu-sheng** [comment]
> It can still support creating dynamic classes for Java6 class after 3.24. But it requires your JRE is above 7.
I agree with the project should NOT stick to Java6 anymore since it is too old. Stick to Java6 means new Java features (source) can not be used.

Agree. The reason I am asking is because `javassist` is added a part of the core of Apache SkyWalking APM. We are using it to work with ByteBuddy by taking both sides advantage. In Agent, we still keep supporting JDK 1.6 today, so our agent dependencies have to stay in that level.

**Comment by wu-sheng** [comment]
Is javassist automatically chosing class version? Or do I need to set manually? If manually, which API should I use?

**Comment by NingZhang-e** [comment]
It will detect the JRE version, then create dynamic class. See below code:

https://github.com/jboss-javassist/javassist/blob/9076bde17537c059aa679bd6c0324bda78bdb088/src/main/javassist/util/proxy/DefineClassHelper.java#L227

https://github.com/jboss-javassist/javassist/blob/9076bde17537c059aa679bd6c0324bda78bdb088/src/main/javassist/bytecode/ClassFile.java#L157

**Comment by candyleer** [comment]
title should be `v3.23`:)
I test the version `3.21.0-GA` is the last version support jdk6 cause `DefineClassHelper ` not exist.
`DefineClassHelper ` dependent on `MethodHandles` which is since above jdk7

**Comment by wu-sheng** [comment]
@chibash Could you consider making JDK6 compatible still working in a release branch? 

`3.21.0-GA` is a 3 years old version. `v3.23` release this year, compiled in 1.6, I hope this could be an option to support version.

SkyWalking community has not decided to move on JDK 1.7 as oldest JDK version requirement.

**Comment by wu-sheng** [comment]
Closing.
