### ISSUE TITLE
JDK11:  Add support for the CONSTANT_Dynamic 17 constant introduced in Java 11

### ISSUE THREAD

**Issue by richbolen** [jboss-javassist/javassist#270]
Java 11 introduced a new constant called Constant_Dynamic (defined here https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.4-210).  When running junit tests using powermock on the Java 11 I get this error:  invalid constant type: 17 at 130.  Support for this constant needs to be added to the ConstPool class.

**Comment by chibash** [comment]
OK, I'll work on this.

**Comment by richbolen** [comment]
I've got it implemented locally. I can submit a PR. I'm still working on the unit test but I could submit what I have.

**Comment by richbolen** [comment]
I don't have permission to submit a PR but would be happy to if you are interested.

**Comment by chibash** [comment]
I think anyone can submit a pull request.  They are not allowed to merge it, though.

**Comment by richbolen** [comment]
Yes. It was a issue with the macos and SSH keys.  Created PR https://github.com/jboss-javassist/javassist/pull/272

**Comment by camron-johnson** [comment]
Is there any update on the addition of Constant_Dynamic to Javassist?

**Comment by Bophie** [comment]
发自我的iPhone


------------------ Original ------------------

**Comment by valfirst** [comment]
@chibash are there any plans to release a new version with this feature?

**Comment by chibash** [comment]
I've just released.  It'll be available from maven within several days.

**Comment by atulrulers** [comment]
is it resolved ? Any ETA ?

**Comment by valfirst** [comment]
yes, it's fixed (I believe someone from maintainers should close it)
