### ISSUE TITLE
How can I use LocalVariable in addCatch

### ISSUE THREAD

**Issue by chdw** [jboss-javassist/javassist#288]
CtMethod m = ...;
m.addLocalVariable("$$$var", pool.get("long"));
m.insertBefore("{$$$var = 123;}");
m.insertAfter("{System.out.println($$$var);}");
m.addCatch("{System.out.println($$$var);}", pool.get("java.lang.RuntimeException"));

In insertBefore or insertAfter, I can use $$$var in code,

But when use $$$var in addCatch, it occur "compile error: no such field: $$$var"

How can I use local variables in addCatch?

**Comment by chibash** [comment]
$$$var is not available within the catch clause because an exception may be thrown before `$$$var` is initialized.  I know it never happens but the JVM (its bytecode verifier) does not allow it.

**Comment by chdw** [comment]
Oh. Is any other way to record milliseconds used by this method?

If method return without exception, insertAfter is work fine.  But when throw exception, I can't get how long it used.

**Comment by chibash** [comment]
A quick fix might be the use of a global variable (or thread local)?

**Comment by chdw** [comment]
I see. Thx.

**Comment by serkan-ozal** [comment]
Hi @chibash , is there any other way to achieve this (without thread-local or global variable)?

**Comment by chibash** [comment]
I don't have any idea...

**Comment by serkan-ozal** [comment]
Hi @chibash I have managed it in the following example https://github.com/serkan-ozal/javassist-issue-report/blob/master/src/main/java/ozal/serkan/javassist/issue/report/LocalVariableAccessInCatch.java But not sure it is the correct way. Any comments?
