### ISSUE TITLE
Tomcat error "Unable to process Jar entry" for all javassist classes

### ISSUE THREAD

**Issue by ryber** [jboss-javassist/javassist#29]
Hello, I recently upgraded javassist in a project that was moving to Java 8. When tomcat starts we get errors for what looks like every class in javassist. I'm pretty sure it's just because tomcat is looking for servlets and such (which it's not going to find anyway) but it's concerning anyway. Here is the error:

13:03:26 starting axplatq
13:03:26 Using CATALINA_BASE:   /www/axplatq
13:03:26 Using CATALINA_HOME:   /www/tomcat/apache-tomcat-7.0.54
13:03:26 Using CATALINA_TMPDIR: /www/axplatq/temp
13:03:26 Using JRE_HOME:        /www/java/jdk1.8.0_05
13:03:26 Using CLASSPATH:       /www/java/jdk1.8.0_05/lib/tools.jar:/www/tomcat/apache-tomcat-7.0.54/bin/bootstrap.jar:/www/tomcat/apache-tomcat-7.0.54/bin/tomcat-juli.jar
13:03:26 Using CATALINA_PID:    /www/axplatq/logs/tomcat.pid
13:03:26 Tomcat started.
13:03:26 INIT: 2015-02-02 12:58:26-06:00
13:03:26 INIT: start() by a909179
13:03:26 INFO: Loaded APR based Apache Tomcat Native library 1.1.30 using APR version 1.3.9.
13:03:26 INFO: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
13:03:26 INFO: Initializing ProtocolHandler ["http-apr-8070"]
13:03:26 INFO: Initialization processed in 1241 ms
13:03:26 INFO: Starting service Catalina
13:03:26 INFO: Starting Servlet Engine: Apache Tomcat/7.0.54
13:03:26 INFO: Deploying web application archive /www/axplatq/webapps/platform.war
13:03:26 SEVERE: Unable to process Jar entry [javassist/ByteArrayClassPath.class] from Jar [jar:file:/www/axplatq/webapps/platform/WEB-INF/lib/javassist-3.19.0-GA.jar!/] for annotations
.... on and on

**Comment by yamass** [comment]
@ryber Have you been able to solve the problem? I am facing the same...

**Comment by ryber** [comment]
We excluded the Jar from Tomcat's scanning: https://tomcat.apache.org/tomcat-8.0-doc/config/jar-scan-filter.html

**Comment by yamass** [comment]
@ryber I solved my problem by updating to apache-tomcat-7.0.59

**Comment by DaiDongLiang** [comment]
I have encountered the same problem in tomcat 8.0.9.
How to solve this problem?

**Comment by chibash** [comment]
Can't you fix the problem by substituting javassist-3.20.0-GA.jar for 3.19.0?

**Comment by jsandeepm** [comment]
Below exclusion fixed my problem  

<dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>5.1.0.Final</version>
            <exclusions>
                <exclusion>
                    <groupId>org.javassist</groupId>
                    <artifactId>javassist</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by zhangfan2015** [comment]
I have involved with it too,updating to tomcat-8.0.33 ,it solved.

**Comment by finansistpavel** [comment]
You can add tomcat.util.scan.StandardJarScanFilter.jarsToSkip= ...,javassist-*.jar  to catalina.properties file  in your tomcat conf folder

**Comment by Valexx55** [comment]
Any of previous replies solved my situation. Using Hibernate, is mandatory to include a javassist jar Using an openshift server, i was getting the same error and could solve it magically, adding  explictly the redhat maven's javassist dependecy  below:

<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.18.1.GA-redhat-1</version>
</dependency>

**Comment by ppazos** [comment]
https://issues.apache.org/jira/browse/WW-4637

catalina.properties file:

tomcat.util.scan.DefaultJarScanner.jarsToSkip=javassist-*.jar
