### ISSUE TITLE
Replace package name

### ISSUE THREAD

**Issue by vvVenom** [jboss-javassist/javassist#295]
How should I replace the package name? The `replaceClassName` method is provided in `CtClass`, but it can only replace class. What if I want to replace all the classes under a package?

**For example:** 
> replace all `com.a.b.*` with `my.a.b.*`

**Comment by chibash** [comment]
You must call `replaceClassName` for each class because there is no way to obtain all the classes included in the given package.

**Comment by vvVenom** [comment]
> You must call `replaceClassName` for each class because there is no way to obtain all the classes included in the given package.

We don't seem to need to know the class under the package, just replace the package name contained in all calls in the bytecode?

**like this:**

> Ljava/lang/String;    ->    Lmy/java/lang/String; 
> Ljava/lang/Void;    ->    Lmy/java/lang/Void;
> Ljava/lang/System;    ->    Lmy/java/lang/System;
> 
> Just need to replace `Ljava/lang/` with `Lmy/java/lang/`

**Comment by chibash** [comment]
But the bytecode is given by a class file.  Each class file contains only the bytecode for that class.
So you must call `replaceClassName` for each class file.

**Comment by vvVenom** [comment]
> But the bytecode is given by a class file. Each class file contains only the bytecode for that class.
> So you must call `replaceClassName` for each class file.

Alright, I will do it by recording the class under each package, thx!
