### ISSUE TITLE
ClassPool get method if not can return null

### ISSUE THREAD

**Issue by 404NotFoundx** [jboss-javassist/javassist#296]
没必要直接报错，有时候我们需要判断类是否存在
```java
ClassPool pool;

CtClass ct = pool.get("com.Main")
if(ct == null){
    ct = pool.makeClass("com.Main");
}
```

**Comment by 404NotFoundx** [comment]
如果是直接报错上面的代码就没办法使用了

**Comment by 404NotFoundx** [comment]
above code just example so i didn t new instance ClassPool or give we a judge empty method

**Comment by chibash** [comment]
Use `ClassPool#find` if you want to get `null` when the specified class does not exist.

(Don't write here in Chinese please.  I asked my Chinese student to translate the posts above.  He said your Chinese text was too casual and hard to understand.  Please try to write text as clearly as possible.  Exchanging ideas among people who don't share the contexts is not as easy as you might expect.)

**Comment by 404NotFoundx** [comment]
sorry my english not good! i mean  if CtClass does not exist return null dont throw Exception. 
```java

//
// code
//
CtClass ctClass = pool.get(fullClassName);
if (ctClass == null) {
    ctClass = pool.makeClass(fullClassName);
}

```

**Comment by 404NotFoundx** [comment]
i need find CtClass in ClassPool

**Comment by chibash** [comment]
??
Try:
```
String name = "com.Main";
URL  url = pool.find(name);
if (url == null)
  ctclass = pool.get(name);
else
  cutlass = pool.makeClass(name);
```

**Comment by 404NotFoundx** [comment]
no no no! i class is String Object not File! i self write ClassLoader use my self ClassLoader create class object. then use CtClass update Class. so find method always null

**Comment by 404NotFoundx** [comment]
[source code](https://github.com/Laniakeamly/poseidon/blob/master/src/main/java/org/laniakeamly/poseidon/framework/sql/Converter.java)

conversion method

**Comment by 404NotFoundx** [comment]
i need judge CtClass does it exist in ClassPool

**Comment by chibash** [comment]
So why are you unhappy with `ClassPool#find`?  It determines whether the specified class is in ClassPool or not.

**Comment by 404NotFoundx** [comment]
```ClassPool#find``` is find in native class not in ram class
my class in ram created

```java

public URL find(String classname) {
    String jarname = "/" + classname.replace('.', '/') + ".class";
    return this.thisClass.getResource(jarname);
}

```

**Comment by chibash** [comment]
OK, then you should define a class implementing the `javassist.ClassPath` interface
and attach an instance of that class to the `javassist.ClassPool` object by calling
`ClassPool#appendClassPath(ClassPath)` or `ClassPool#insertClassPath(ClassPath)`.

**Comment by 404NotFoundx** [comment]
ok

**Comment by 404NotFoundx** [comment]
think you
