### ISSUE TITLE
The method SerialVersionUID.calculateDefault() should be public

### ISSUE THREAD

**Issue by siom79** [jboss-javassist/javassist#30]
Currently the method `SerialVersionUID.calculateDefault()` is package protected. Making it public would allow clients of the library to calculate the serialVersionUID without manipulating the instance of `CtClass`. This helps libraries like [japicmp](https://github.com/siom79/japicmp) to determine if the default serialVersionUID of a class has changed.

**Comment by chibash** [comment]
I made `calculateDefault()` public.

**Comment by siom79** [comment]
Thank you.
