### ISSUE TITLE
How To Launch Execute?

### ISSUE THREAD

**Issue by 90mindblogspotcom** [jboss-javassist/javassist#313]
I dont know how to start java assist. I tried javassist.jar but nothing happened. I am using windows.

**Comment by chibash** [comment]
Try:
```
% java -jar javassist.jar
```
It will print the version number.

**Comment by 90mindblogspotcom** [comment]
So you say my java version is wrong and i have to use an older version?

**Comment by chibash** [comment]
Ah... since javassist is a library, there is no way to *start* javassist.  You have to write a main program using javassist.  But you can run it by `java -jar javassist.jar`, which will print its version number (not your JVM's version).   Yes, this is useless but, if you ask me how to run javassist, this is the only answer I can give you. ;-)

Seriously, what do you want to do with javassist?

**Comment by cookiedragon234** [comment]
So you’re telling me that the entire functionality of javassist is to print its version number? How did this take 922 commits to achieve? Perhaps you need to rethink your product design.

**Comment by chibash** [comment]
My apology for my joke.  @90mindblogspotcom, it would be helpful to read [https://github.com/jboss-javassist/javassist/blob/master/Readme.html](url). It mentions how to run several sample programs written with Javassist.   Anyway, Javassist is not a standalone application.  It's a library.  So I need to know what you expect to do with Javassist before giving you more meaningful advice.

In fact, if you look at Javassist as a standalone application, its only functionality is to print its version number!

**Comment by 90mindblogspotcom** [comment]
I what, i using a different software and this error happened; what shall i do and coders of this how they coded it if there is errors in it. You know i edit a class file and it says there is error even i didnt edit it. If there is error how it is compiled?



Error Failed to find end label for variable 3. What shall i do? If i delete errors will it work?

DUP
ICONST_3
LDC "Toxic"
AASTORE
INVOKEVIRTUAL com/pixelmonmod/pixelmon/battles/attacks/Attack.isAttack([Ljava/lang/String;)Z
IFEQ C
B:
ICONST_1
GOTO D
C:
ICONST_0
D:

!---(ERROR>>> ISTORE 3 <<

ILOAD 3
IFNE E
ALOAD 2
ICONST_1
ANEWARRAY com/pixelmonmod/pixelmon/enums/EnumType
DUP
ICONST_0
GETSTATIC com/pixelmonmod/pixelmon/enums/EnumType.Grass Lcom/pixelmonmod/pixelmon/enums/EnumType;
AASTORE
INVOKEVIRTUAL com/pixelmonmod/pixelmon/battles/controller/participants/PixelmonWrapper.hasType([Lcom/pixelmonmod/pixelmon/enums/EnumType;)Z
IFEQ E
ALOAD this
INVOKESTATIC com/pixelmonmod/pixelmon/entities/pixelmon/abilities/Overcoat.isPowderMove(Lcom/pixelmonmod/pixelmon/battles/attacks/Attack;)Z
IFEQ E
ICONST_1
ISTORE 3

**Comment by Col-E** [comment]
> i using a different software and this error happened

Please keep bug reports to their respective projects

**Comment by 90mindblogspotcom** [comment]
Leave me alone, you are creeping me

**Comment by cookiedragon234** [comment]
I think Col-E might be in breach of github community guidelines for “creeping” people

**Comment by Col-E** [comment]
Oh no! :disappointed:

**Comment by RenFontes** [comment]
> So you’re telling me that the entire functionality of javassist is to print its version number? How did this take 922 commits to achieve? Perhaps you need to rethink your product design.

Is this intentional /r/programmingcirclejerk material? 😂

**Comment by chibash** [comment]
> I what, i using a different software and this error happened; what shall i do and coders of this how they coded it if there is errors in it. You know i edit a class file and it says there is error even i didnt edit it. If there is error how it is compiled?

OK, so did you use a disassembler for Java bytecode?  If that disassembler reports the class file is broken as below, the class file is really broken or that disassembler has a bug.  I cannot tell you more than that unless you give me the name of that disassembler and the class file you tried to disassemble.

That class file might be broken.  It might not be generated by the Java compiler from Java source.  Some mechanical bytecode generator might generate that class file.  In this case, that bytecode generator might have a bug.  For example, some bytecode generator generates a class file that is compatible with only earlier versions of Java (or the JVM).

> DUP
> ICONST_3
> LDC "Toxic"
> AASTORE
> INVOKEVIRTUAL com/pixelmonmod/pixelmon/battles/attacks/Attack.isAttack([Ljava/lang/String;)Z
> IFEQ C
> B:
> ICONST_1
> GOTO D
> C:
> ICONST_0
> D:
>
> !---(ERROR>>> ISTORE 3 <<

Is this the real output from that disassembler?  The last line does not tell me what is wrong.  I suppose that the disassembler does not mention the class file is broken but it mentions something different.

> Error Failed to find end label for variable 3. What shall i do? If i delete errors will it work?

If you delete the line "istore 3", then the error will disappear but the resulting code would not run.

**Comment by Col-E** [comment]
> Is this the real output from that disassembler?

The last line is added by him. My disassembler supports named labels & variables which is why it doesn't look like something out of `javap`

The issue he brought up was fixed a few days ago.

**Comment by chibash** [comment]
Well, every software has bugs.
So, the problem in the output shown above has been fixed.
Is @90mindblogspotcom also happy with this? 
Or, does @90mindblogspotcom have a further problem?

**Comment by dominikaaaa** [comment]
I feel this issue can be closed as resolved :p
