### ISSUE TITLE
How to release the ClassPool file handles?

### ISSUE THREAD

**Issue by Drakyen** [jboss-javassist/javassist#321]
So, I've been struggling for a while with an issue where I'm unable to access a file after accessing it with Javaassist. Here's a short test program I made to show the issue:

```
    public static void main(String[] var) throws NotFoundException, IOException, CannotCompileException {

        ClassPool classPool = new ClassPool();

        ClassPath classPath = classPool.appendClassPath("test.jar");

        CtClass klass = classPool.get("a");

        klass.detach();

        klass.writeFile();

        classPool.removeClassPath(classPath);

        File f = new File("test.jar");

        if(f.renameTo(new File("testRename.jar"))){
            System.out.println("Renamed");
        } else{
            System.out.println("Failed to rename");
        }
}
```

This is failing to rename the file, and even after looking through the documentation for some time, I'm not sure how to fix it. Is there something simple I'm missing, or is it a deeper issue with something here?

**Comment by Raymond-Naseef** [comment]
Hi.  I copied your code and ran it modifying the pathname for JAR and class to a ones I have, and it worked.  If you create a project I can run, I'd be happy to look into it for you.

Just one question: the jar file is not the file this main() method is being run in, right?

**Comment by Drakyen** [comment]
That's odd. I can try compiling for you tomorrow (it's pretty late here), but I suspect that won't change it. 

One thing to note that might be affecting it is that I'm on Windows, which as far as I could find out, means that files can only be accessed by a single "thing" at once, meaning that all file accessors have to be closed when done with, whereas other OS's don't have that limitation(?). 

If you're on Windows too, and it works for you, then I'm very confused, and I'll have to check and give you my exact project settings and PC specs.

**Comment by Raymond-Naseef** [comment]
I am currently using MacBook Pro.  I know Java has some issues with it's
file management: it hasn't actually locked and release files on the disk as
you would expect.  We had such an issue in 2003 trying to use a file as a
method to synchronize operations, and that did not work properly.

Is it possible there is some issue because of java garbage collection?

**Comment by Drakyen** [comment]
Not sure.. I've tried many things, both with and without calling gc(), and haven't managed to get anywhere. Even doing deleteOnExit() on the file doesn't work ~ I assume because the deletion is called right before the virtual machine actually cleans up and releases any remaining handles

**Comment by Drakyen** [comment]
Okay, so after some more testing, it appears that `writeFile()` is what's causing issues. Looking into it a bit, I don't see any obvious problems, but somewhere in there it seems that it's not properly letting go of the original class, since without calling `writeFile()` (with or without an output dir), my code succeeds. I'm going to continue looking to see if I can find what's happening.

**Comment by Drakyen** [comment]
Yeah, I have no idea why it's happening. Been searching through the source of `writeFile()` and `setName()` and I can see literally nothing that's even using a reference to the original jar (aside from `writeFile()` copying from it if the class hasn't been modified, but that's closed immediately), so I have no idea what's going on here.....

**Comment by chibash** [comment]
Do this first:
`ClassPool.cacheOpenedJarFile = false`

Its default value is `true`.  I think the reason of your problem is obvious.

**Comment by Drakyen** [comment]
Ah okay, awesome! I'm not entirely sure whether I should be annoyed with myself for not finding that or whether it was too obscure to expect myself to notice. Either way, I appreciate the help!

**Comment by chibash** [comment]
Well, I also found this static variable when reviewing the code to figure out what was going on in your case.
None remembers or notices such a detail of this not-small library...

**Comment by learncatcat** [comment]
> Do this first: `ClassPool.cacheOpenedJarFile = false`
> 
> Its default value is `true`. I think the reason of your problem is obvious.

This code works! I had the same problem, cannot delete jar file.
