### ISSUE TITLE
javassist.CannotCompileException: cannot find com.google.android.exoplayer2.Format

### ISSUE THREAD

**Issue by Kimiar** [jboss-javassist/javassist#359]
It is a bug I guess. 
When I use javassist to change the ByteCode of ExoPlayer（ExoPlayer is Gradle dependencies at JCenter repository）. The error happened.
I use the javassist in Gradle Plugin，like this:
plugin.groovy
```
ClassPool classPool = ClassPool.getDefault()

def classFile = new ClassFile(new DataInputStream(new BufferedInputStream(is)))
        def ctClass = classPool.get(classFile.name)
        //
        if (ctClass.isFrozen()) {
            ctClass.defrost()
        }
        //
        def method = ctClass.getDeclaredMethod("configure")
        // some java code String
        def body = ''
        method.insertBefore(body)
```
ExoPlayer.audio.DefaultAudioSink
```
public void configure(Format inputFormat, int specifiedBufferSize, @Nullable int[] outputChannels)
      throws ConfigurationException {
}
```

The biggest different is that the DefaultAudioSink is in ExoPlayer-core.aar file, but the Format.java is in ExoPlayer-common.aar file。
I tried other class file of Exoplayer, javassist always can't find the method's param if they are not in same file.
Anybody knows?

**Comment by NingZhang-e** [comment]
Any stacktrace?
What is the runtime version of Android, identical to which JDK version?

**Comment by Kimiar** [comment]
> Any stacktrace?
> What is the runtime version of Android, identical to which JDK version?

It even can't pass the gradle build. The error was reported by Gradle when I build the code. No more error message.
I solved it by add the .jar file at the harddisk Location. like this 
`classPool.appendClassPath("C:\\Users\\Administrator\\.gradle\\caches\\transforms-2\\files-2.1\\a796fe6f05d35b507e55b359d6efe8b8\\jetified-exoplayer-common-2.12.2\\jars\\classes.jar")`

Maybe it is my fault. 
Thanks for your response!
