### ISSUE TITLE
does this project support android?

### ISSUE THREAD

**Issue by zhaoguomanong** [jboss-javassist/javassist#360]
I am using org.javassist:javassist:3.27.0-GA in android studio(build android apk).

below is my code:

    public static abstract class Calculator {
         public abstract int sum(int a, int b);
    }

    private void reflectionTest() {
        try {
            ProxyFactory factory = new ProxyFactory();
            factory.setSuperclass(Calculator.class);
            factory.setHandler(new MethodHandler() {
                @Override
                public Object invoke(Object self, Method method, Method proceed, Object[] args) throws Throwable {
                    if (TextUtils.equals(method.getName(), "sum")) {
                        int a = (int) args[0];
                        int b = (int) args[1];
                        return a + b;

                    }
                    return null;
                }
            });
            Class aClass = factory.createClass();
            Object object = aClass.newInstance();
        } catch (Exception e) {
            Log.e(TAG, "reflection error", e);
        }
    }

but I got the exception when the apk run on android device, is this a bug? or this jar not support android platform??.

02-05 16:48:47.264  3142  3142 E Test    : reflection error
02-05 16:48:47.264  3142  3142 E Test    : java.lang.NullPointerException: Attempt to read from null array
02-05 16:48:47.264  3142  3142 E Test    : 	at javassist.util.proxy.SecurityActions.getCallerClass(SecurityActions.java:54)
02-05 16:48:47.264  3142  3142 E Test    : 	at javassist.util.proxy.DefineClassHelper$Java7.defineClass(DefineClassHelper.java:174)
02-05 16:48:47.264  3142  3142 E Test    : 	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
02-05 16:48:47.264  3142  3142 E Test    : 	at javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:154)
02-05 16:48:47.264  3142  3142 E Test    : 	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:640)
02-05 16:48:47.264  3142  3142 E Test    : 	at javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:562)
02-05 16:48:47.264  3142  3142 E Test    : 	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:481)
02-05 16:48:47.264  3142  3142 E Test    : 	at com.android.cungui.screeninfo.MainActivity.reflectionTest(MainActivity.java:102)
02-05 16:48:47.264  3142  3142 E Test    : 	at com.android.cungui.screeninfo.MainActivity.onResume(MainActivity.java:39)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.app.Activity.performResume(Activity.java:7939)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4223)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4265)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.os.Looper.loop(Looper.java:214)
02-05 16:48:47.264  3142  3142 E Test    : 	at android.app.ActivityThread.main(ActivityThread.java:7386)
02-05 16:48:47.264  3142  3142 E Test    : 	at java.lang.reflect.Method.invoke(Native Method)
02-05 16:48:47.264  3142  3142 E Test    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-05 16:48:47.264  3142  3142 E Test    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by NingZhang-e** [comment]
I think your Android SDK is running based on same compliance level as Java7 or 8.
Javassist code:
`class SecurityActions extends SecurityManager`

In JDK java.lang.SecurityManager:
`public class SecurityManager {
      protected native Class<?>[] getClassContext();
}`

So it is hard to troubleshoot on J2SE environment since it can not be re-produced..
Please check the underlying code of Android SDK or check if there is any special configuration needed..

**Comment by zhaoguomanong** [comment]
> I think your Android SDK is running based on same compliance level as Java7 or 8.
> Javassist code:
> `class SecurityActions extends SecurityManager`
> 
> In JDK java.lang.SecurityManager:
> `public class SecurityManager { protected native Class<?>[] getClassContext(); }`
> 
> So it is hard to troubleshoot on J2SE environment since it can not be re-produced..
> Please check the underlying code of Android SDK or check if there is any special configuration needed..

I checked the SecurityManager on android AOSP Project: 

https://android.googlesource.com/platform/libcore.git/+/refs/heads/master/ojluni/src/main/java/java/lang/SecurityManager.java#67

getClassContext always returns null.

so this project will not work on android devices?

**Comment by zhaoguomanong** [comment]
I tried to build this project's java source code on android, there are too many compile errors, 

all below classes can't be found on android, so I guess this jar can't be run on android phones?

import java.lang.instrument.ClassDefinition;
import java.lang.instrument.Instrumentation;
import java.lang.instrument.UnmodifiableClassException;
import java.lang.management.ManagementFactory;

import com.sun.jdi.Bootstrap;
import com.sun.jdi.ReferenceType;
import com.sun.jdi.VirtualMachine;
import com.sun.jdi.connect.AttachingConnector;
import com.sun.jdi.connect.Connector;
import com.sun.jdi.connect.IllegalConnectorArgumentsException;
import com.sun.jdi.event.Event;
import com.sun.jdi.event.EventIterator;
import com.sun.jdi.event.EventQueue;
import com.sun.jdi.event.EventSet;
import com.sun.jdi.event.MethodEntryEvent;
import com.sun.jdi.request.EventRequest;
import com.sun.jdi.request.EventRequestManager;
import com.sun.jdi.request.MethodEntryRequest;

**Comment by NingZhang-e** [comment]
If you look at: https://github.com/jboss-javassist/javassist/blob/master/pom.xml#L288
I think the answer is no.

I am not expert about Android.

Just one question:
When Android SDK package jars to APK, does it convert the bytecode? Seems it is out of code of javassist.

**Comment by zhaoguomanong** [comment]
Sorry, I am not sure whether Android convert the bytecode or not.
Finally, I gave up using this jar on Android. Thanks for your reply.


在 2021年3月2日星期二，Ning Zhang <notifications@github.com> 写道：
