### ISSUE TITLE
[3.27.0-GA] spurious javassist.NotFoundException

### ISSUE THREAD

**Issue by laeubi** [jboss-javassist/javassist#362]
I'm using javassist to replace some methods in a compiled class file.

From time to time I encounter a NotFoundException for different classes, if i simply rerun the process with the same parameters everything works, or I need to run it 2 or 3 times in a row until it succeeds.

What I have tried so far:

1. I'm running everything in a single thread to prevent any multi-threading issues
2. I'm only using precompiled classes and jars and write the transformed data into a temporary location to make sure I d not modify any data by accident

**Comment by laeubi** [comment]
@chibash any hint how this can be debugged? This is really annoying and really hinders using javassist...

**Comment by chibash** [comment]
Writing a very short program that simply reproduce this bug is always the first step to fix such a bug.
Have you written it yet?

**Comment by laeubi** [comment]
The problem is that the problem only occurs in a bigger setup and not always (sometimes it occurs 4 - 5 times in a row sometimes never) that's why I wonder if I can enable some logging/whatever so get a better feeling about the context.
In the meanwhile I have upgraded to 3.28.0-GA to see if it possibly was already fixed there (but as noted as it not occurs always its hard to tell if that fixes it).

**Comment by laeubi** [comment]
Also happens with 3.28.0-GA ... I'll try to create an as small as possible test case.

**Comment by laeubi** [comment]
I have created a Testscript, you need a bunch of files (I choose an eclipse install see comment in code) that leads to errors at random files with different errors:

```
Iteration 0: Succeeds!
Iteration 1: ... failed [file index: 20][com.google.guava_27.1.0.v20190517-1946.jar] javassist.CannotCompileException: [source error] javassist.NotFoundException: java.util.Optional
Iteration 2: ... failed [file index: 38][org.eclipse.oomph.resources_1.15.0.v20210211-0559.jar] java.lang.RuntimeException: javassist.NotFoundException: org.eclipse.core.resources.IProjectDescription
Iteration 3: ... failed [file index: 38][org.eclipse.oomph.resources_1.15.0.v20210211-0559.jar] java.lang.RuntimeException: javassist.NotFoundException: org.eclipse.core.resources.IFolder
Iteration 4: ... failed [file index: 39][org.eclipse.wst.common.ui_1.2.100.v202101112327.jar] javassist.CannotCompileException: [source error] javassist.NotFoundException: org.eclipse.wst.common.ui.internal.viewers.SelectSingleFileView$Listener
```

The result may vary from run to run ...  [Bug362.java.zip](https://github.com/jboss-javassist/javassist/files/6494224/Bug362.java.zip)

Let me know if you need any further details.

**Comment by chibash** [comment]
Your way of using LoaderClassPath is wrong.
Look at http://www.javassist.org/html/javassist/LoaderClassPath.html
Because your code uses a `URLClassLoader` object and it is referred to through a local variable,
the ClassPool loses its access to that URLClassLoader after it is garbage collected.
A workaround is to use `ClassPool#appendClassPath(String)`.

**Comment by laeubi** [comment]
Thanks for the hint that seems to be the issue! I have created a simple Workaround the following way:

```
final class StrongLoaderClassPath extends LoaderClassPath {

	private ClassLoader cl;

	public StrongLoaderClassPath(ClassLoader cl) {

		super(cl);
		this.cl = cl;
	}

	public ClassLoader getCl() {

		return cl;
	}
}
```
