### ISSUE TITLE
java.lang.VerifyError: StackMapTable error: bad offset

### ISSUE THREAD

**Issue by aliab01** [jboss-javassist/javassist#37]
Hi Shigeru,

Please excuse me if this is not the right place to ask the question. I tried your github page to see if I can send email.

I used CtMethod.insertBefore to the following API during JVM startup and I end having following error. Can you please give me some help/hint/clue, what could be the issue?
BTW: I'm trying to instrument ojdbc7.jar
I'm suspecting, it could be an issue in javassist library.

Caused by: java.lang.VerifyError: StackMapTable error: bad offset
Exception Details:
  Location:
    oracle/jdbc/driver/OracleStatement.getMoreResults(I)Z @0: aload_0
  Reason:
    Invalid stackmap specification.
  Current Frame:
    bci: @166
    flags: { }
    locals: { 'oracle/jdbc/driver/OracleStatement', integer, 'java/lang/Object' }
    stack: { }
  Bytecode:
    0000000: 2a13 073a 1307 3c13 0762 1307 7e04 bd03
    0000010: 4459 03bb 05b8 591b b707 6a53 b807 614d
    0000020: 2cb2 0757 a500 0b2c c007 47b6 075a ac00
    0000030: 2a13 073a 1307 3c13 0762 1307 7e04 bd03
    0000040: 4459 03bb 05b8 591b b707 6a53 01b8 0752
    0000050: 4d2c b207 57a5 000f 2cc0 0747 b607 5aa7
..........

 Exception Handler Table:
    bci [100, 359] => handler: 359
    bci [48, 466] => handler: 466
  Stackmap Table:
    full_frame(@47,{Object[#807],Integer,Object[#836]},{})
    same_frame(@98)

**Comment by aliab01** [comment]
@chibash By this way I took a look at https://issues.jboss.org/browse/JASSIST-241
I also verified the javassist I have in my environment, Its javassist 3.9 GA. Looks like JAVASSIST-241 is not fully fixed yet.

**Comment by aliab01** [comment]
@chibash never mind , the issue got resolved after applying https://issues.jboss.org/browse/JASSIST-241 on top of 2.19-GA. I'm closing this.

**Comment by sajalag76** [comment]
@aliab01 I'm also facing the same java.lang.VerifyError error when I'm using CtMethod.insertAfter method to modify one of the methods in my java web application. I have read the link you have posted in your last comment but still I have no clue on how I can modify the insertAfter method to work properly. Can you assist me on this?

**Comment by vrocky** [comment]
I learned that if we use insertAfter with the 'redundant' parameter as mentioned in the documentation this issue doesn't occur. I resolved this 

by changing 
```
    ctBehavior.insertAfter(exit, true, true);
```
to
``` 
  ctBehavior.insertAfter(exit, true, ctClass.isKotlin());
```
