### ISSUE TITLE
The class javassist.Modifier should provide the methods isBridge() and isSynthetic()

### ISSUE THREAD

**Issue by siom79** [jboss-javassist/javassist#39]
Classes, methods and fields can be marked by the compile with the property flags ACC_BRIDGE and ACC_SYNTHETIC (see [The class file format](https://jcp.org/aboutJava/communityprocess/maintenance/jsr924/JVMS-SE5.0-Ch4-ClassFile.pdf)). In order to query if this flag is set or not, the class `javassist.Modifier` should provide the methods `isBridge()` and `isSynthetic()`.

**Comment by chibash** [comment]
javassist.Modifier was designed to be compatible to java.lang.reflect.Modifier.
So no isBridge() or isSynthetic().
javassist.bytecode.AccessFlag has BRIDGE and SYNTHETIC fields.

**Comment by jose** [comment]
Hi,

I've been trying to write some code to skip synthetic methods, however does not seem to be working.
suppose I have the following class:
```
public class SyntheticExample {
  public static void main(String[] args) {
    System.out.println(SyntheticExample.class);
  }
}
```

Compiling it with Java 1.4 (yeah, it has to be 1.4) I get the following bytecode:
```
$ javac -source 1.4 -target 1.4 SyntheticExample.java
$ javap -v SyntheticExample

public class SyntheticExample
  flags: ACC_PUBLIC, ACC_SUPER

  public static void main(java.lang.String[]);
    flags: ACC_PUBLIC, ACC_STATIC

  static java.lang.Class class$(java.lang.String);
    flags: ACC_STATIC
    Synthetic: true
```

and here the code to skip synthetic methods:
```
for (CtMethod cb : ct.getDeclaredMethods()) {
  if ( (cb.getMethodInfo().getAccessFlags() & AccessFlag.SYNTHETIC) != 0 ) {
     continue;
  }
  // do stuff
}
```

it seems that `cb.getMethodInfo().getAccessFlags()` is returning 8 (i.e., AccessFlag.STATIC) and `cb.getMethodInfo().getAccessFlags() & AccessFlag.SYNTHETIC` returns 0.


am I doing something wrong? how can I identify (and skip) synthetic methods?

**Comment by chibash** [comment]
To do that, you have to check the existence of the Synthetic attribute.

**Comment by chibash** [comment]
Check MethodInfo#getAttribute(SyntheticAttribute.tag) != null

**Comment by FlorianLoch** [comment]
@chibash your strategy doesn't work for me... I am sure, I am working on a class with synthetic methods (java.lang.StringBuffer compiled with Java 8) - but the list of attributes retrieved via getAttribute() doesn't contain "Synthetic". Any idea? Were there related changes in the codebase?

**Comment by kensei62** [comment]
getAttribute(SyntheticAttribute.tag) didn't work for me either. Checking the modifiers did work:

(method.getModifiers() & AccessFlag.SYNTHETIC) != 0

**Comment by chibash** [comment]
@kensei62 , you are right.  I found in The Java® Virtual Machine Specification 4.7.8:

> A class member that does not appear in the source code must be marked using a Synthetic attribute, or else it must have its ACC_SYNTHETIC flag set. 

So both `getAttribute(SyntheticAttribute.tag)` and `(method.getModifiers() & AccessFlag.SYNTHETIC) != 0` must be checked.
