### ISSUE TITLE
Estimated release date of javassist 3.20-GA?

### ISSUE THREAD

**Issue by aliab01** [jboss-javassist/javassist#40]
Greetings @chibash,

Can you please let us know the estimated release date of javassist 3.20-GA?
We are waiting for the fix https://issues.jboss.org/browse/JASSIST-241 in the new release of javassist

Regards
Abed

**Comment by aliab01** [comment]
Hi @chibash 

I'm following-up on the previous query that I have posted last week. Can you respond please.

Regards
Abed

**Comment by aliab01** [comment]
Hi @chibash 

Any update please?

Thanks
Abed

**Comment by chibash** [comment]
Probably June?  Is it too late?

**Comment by aliab01** [comment]
Hi @chibash 

Thank you for getting back to me. 
We have a release coming in Jun, is there anyway to expedite the process to release the jar(3.20) by end of May?

Thanks
Abed

**Comment by chibash** [comment]
I see.  What about releasing the end of May or early June (if I have time)?

**Comment by aliab01** [comment]
That helps @chibash . 

Thank you
Abed

**Comment by aliab01** [comment]
Good Morning @chibash 

Gentle reminder for 3.20-GA release.

Thanks
Abed

**Comment by chibash** [comment]
Yes, you're right.  I'll do it soon...

**Comment by abedali** [comment]
Thanks @chibash 

Hopefully we would expect the release in the end of this week.

Regards
Abed

**Comment by chibash** [comment]
I'm doing now...

**Comment by chibash** [comment]
Done.  It will be also available soon from maven repo.

**Comment by aliab01** [comment]
Thank you @chibash 

Appreciated for taking time and responding to our request.

Thanks
Abed
