### ISSUE TITLE
Bad OSGi metadata in https://repo1.maven.org/maven2/org/javassist/javassist/3.30.0-GA

### ISSUE THREAD

**Issue by merks** [jboss-javassist/javassist#471]
This just-released version

https://repo1.maven.org/maven2/org/javassist/javassist/3.30.0-GA

has this erroneous requirement in the MANIFEST.MF:
```
Require-Capability: osgi.ee;filter:="(osgi.ee=UNKNOWN)"
```

The previous released version

https://repo1.maven.org/maven2/org/javassist/javassist/3.29.2-GA/

has this valid requirement in the MANIFEST.MF:
```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
```

I don't think the 3.30.0-GA version can be used in any OSGi application.

**Comment by chibash** [comment]
Any idea to fix this?  Is pom.xml broken?

**Comment by merks** [comment]
I couldn't figure how how the MANIFEST.MF is being generated and hence I could not determine the source of the wrong information...

Is it generated from here?

https://github.com/jboss-javassist/javassist/blob/f74619e8ba2ba05a44fabaefd2af1516dadc75aa/pom.xml#L220-L244

Or is it generated using this?

https://github.com/jboss-javassist/javassist/blob/master/build.xml

Both those files still have `3.29.2-GA` so I'm really confused where `3.30.0-GA` comes from and how it's built.

**Comment by merks** [comment]
Cloning the repo and running the build produces this:

![image](https://github.com/jboss-javassist/javassist/assets/208716/56c77d18-fb6e-4f9e-8f82-921f8c3b6c53)

And that appears to be correct.  I just don't know how the 3.30.0-GA versions is being created...

**Comment by merks** [comment]
Maybe the problem is using an old version of this

https://repo1.maven.org/maven2/org/apache/felix/maven-bundle-plugin/3.0.0/

when this is the latest version:

https://repo1.maven.org/maven2/org/apache/felix/maven-bundle-plugin/5.1.9/

Maybe you are compiling for Java 11 or 17 and that old plugin don't recognize that?

**Comment by laeubi** [comment]
> And that appears to be correct

The pom.xml says the project is at Java 11

https://github.com/jboss-javassist/javassist/blob/f74619e8ba2ba05a44fabaefd2af1516dadc75aa/pom.xml#L154-L155

so it does not seem correct to say it is java 8.

**Comment by chibash** [comment]
My apology.  The last commit has not been pushed.
Anyway, I used pom.xml and Java 21 to generate the 3.30.0-GA release.

**Comment by chibash** [comment]
Thanks, @merks You're right.

**Comment by merks** [comment]
Thank you for publishing the new version immediately:

https://repo1.maven.org/maven2/org/javassist/javassist/3.30.1-GA/

**Comment by merks** [comment]
Of course this can be closed now. Happy Holidays.  🎆
