### ISSUE TITLE
License condition

### ISSUE THREAD

**Issue by PavlinaDostalova** [jboss-javassist/javassist#474]
Hi,
I am not sure, if I can really choose under which license I will be redistribute ...
In some cases it looks like, that we have to fullfill license condition of all licenses.
MPL 1.1 is connected with JBOSS - <license>
      <name>MPL 1.1</name>
      <url>http://www.mozilla.org/MPL/MPL-1.1.html</url>
    </license>
    <!-- this is the license under which javassist is distributed when
	 it is bundled with JBoss

But on github, you have little bit different info. Please, could you clarify it to me?

**Comment by chibash** [comment]
> MPL 1.1 is connected with JBOSS - MPL 1.1
> http://www.mozilla.org/MPL/MPL-1.1.html

Can you show me why you thought MPL1.1 is connected with JBOSS?

```
<!-- this is the license under which javassist is distributed when
it is bundled with JBoss
```

Where did you find this sentence?  Since it starts with `<!--`, it is a comment and so obsolete.
You can redistribute the software as its License mentions.

**Comment by PavlinaDostalova** [comment]
https://central.sonatype.com/artifact/org.javassist/javassist/3.28.0-GA?smo=true

**Comment by chibash** [comment]
OK, thanks.  I think the description in pom.xml is consistent with License.html.
MPL is the original license.  LGPL was used when it is distributed as part of JBoss.  Apache was later added as the third option.
But you can freely choose either MPL, LGPL, or Apache.

**Comment by PavlinaDostalova** [comment]
OK, thanks for explanation.
