### ISSUE TITLE
Asking about licenses issue

### ISSUE THREAD

**Issue by gumingyu6689** [jboss-javassist/javassist#483]
Hello ，
I am try to use the javassist：3.26.0-GA,but license 
<img width="542" alt="image" src="https://github.com/jboss-javassist/javassist/assets/45792624/3d42e6a0-d2d5-4e81-b81f-c0cd9d26d7b5">
so I double check with Git repo:https://github.com/jboss-javassist/javassist/blob/master/README.md
This software is distributed under the Mozilla Public License Version 1.1, the GNU Lesser General Public License Version 2.1 or later, or the Apache License Version 2.0.
So that mean we can choose one of this three license when  we reference this open source component in our code?

**Comment by chibash** [comment]
When you use Javassit, you don't have to choose one of the three licenses.
You must choose one when you *distribute* your software with Javassist source code and/or its binary.
I don't think you have to choose a license when you ask your users to separately download Javassist jar file from maven repo.
