### ISSUE TITLE
CtClass.getDeclaredMethods() returns duplicated methods

### ISSUE THREAD

**Issue by laurre** [jboss-javassist/javassist#55]
As stated in the documentation, CtClass.getDeclaredMethods() should return only methods declared in the class, not the inherited ones. When I try to get the methods declared in java.lang.StringBuffer, I get some duplicated methods. Test case :

ClassPool p = ClassPool.getDefault();
CtClass clazz = p.get("java.lang.StringBuffer");
CtMethod[] methods = clazz.getDeclaredMethods();
for (CtMethod method : methods) {
    System.out.println(method);
}

I get for example these two methods in the console:
javassist.CtMethod@77c141ce[public synchronized append (I)Ljava/lang/StringBuffer;]
javassist.CtMethod@77c141ce[public volatile append (I)Ljava/lang/AbstractStringBuilder;]

java.lang.AbstractStringBuilder seems to be an internal class, but I don't understand why I get these duplicated methods.

**Comment by chibash** [comment]
I think the second append() is a bridge method, which is added by the compiler.
Since it is a method declared in StringBuffer, I'm not sure CtClass.getDeclaredMethods() should hide this bridge method. 
What do you think?
