### ISSUE TITLE
Javassist source code translator 

### ISSUE THREAD

**Issue by Grater** [jboss-javassist/javassist#61]
Is there any source code translator which translates a given source code into javassist compatible code. For example,  I understand javassist cannot intercept final methods. The translator should be able to translate a final class into functional equivalent non final class. 

I understand that this is not right way to ask such question. But I couldnt find any javassist interest forumn. Any help is highly appreciated.

**Comment by chibash** [comment]
Although I don't really understand what "intercepting a final method" means, it should be possible to turn a final class into a non-final one by calling CtClass#setModifiers(int).  The same for final methods.
