### ISSUE TITLE
Primitive array return values cause invalid cast to Object

### ISSUE THREAD

**Issue by wsaar** [jboss-javassist/javassist#63]
"(Object) $_" causes "invalid cast" when the return value is a byte array.

**Comment by chibash** [comment]
$_ is a write-only variable.  Can you post a test program reproducing this bug?

**Comment by wsaar** [comment]
Hmm, I thought you could read $_ to inspect return values in insertAfter? (seems to work except for this)

Managed to work around it, but uploaded a reproducer test here
https://github.com/wsaar/fragments/blob/master/JavassistInvalidCastTest.java

**Comment by chibash** [comment]
The reported problem was a bug.  Thanks.
I've fixed.
