### ISSUE TITLE
java.lang.ExceptionInInitializerError when instrumenting the constructor of an inner class

### ISSUE THREAD

**Issue by jose** [jboss-javassist/javassist#71]
Hi,

I've been working on a library that reports the line coverage of unit test cases, and it uses Javassist to instrument the java code. It works pretty well, actually Javassist API is very easy to use (thanks for that), but there is a weird case that leads to a `java.lang.ExceptionInInitializerError`. Let suppose that I'm trying to get the coverage of the following class:
```

public abstract class Foo {

  public static final ExtendsFoo extendsFoo = new ExtendsFoo();

  protected Foo() {
    super();
  }

  public static class ExtendsFoo extends Foo {
    public ExtendsFoo() {
      super();
    }
  }
}
```
using the following test case:
```

import static org.junit.Assert.assertNotNull;
import org.junit.Test;

public class TestFoo {

  @Test
  public void test() {
    Foo.ExtendsFoo other_foo = new Foo.ExtendsFoo();
    assertNotNull(other_foo);
  }
}
```
after instrument the class under test, I got the following bytecode
```
public abstract class Foo {
  public static final Foo$ExtendsFoo extendsFoo;

  public static final int[] $__my_field;

  protected Foo();
    Code:
       0: getstatic     #26                 // Field $__my_field:[I
       3: iconst_0      
       4: dup2          
       5: iaload        
       6: iconst_1      
       7: iadd          
       8: iastore       
       9: aload_0       
      10: invokespecial #1                  // Method java/lang/Object."<init>":()V
      13: getstatic     #26                 // Field $__my_field:[I
      16: iconst_1      
      17: dup2          
      18: iaload        
      19: iconst_1      
      20: iadd          
      21: iastore       
      22: return        
    LineNumberTable:
      line 7: 0
      line 8: 13

  static {};
    Code:
       0: iconst_2      
       1: newarray       int
       3: putstatic     #26                 // Field $__my_field:[I
       6: new           #2                  // class Foo$ExtendsFoo
       9: dup           
      10: invokespecial #3                  // Method Foo$ExtendsFoo."<init>":()V
      13: putstatic     #4                  // Field extendsFoo:LFoo$ExtendsFoo;
      16: return        
    LineNumberTable:
      line 4: 6
}

public class Foo$ExtendsFoo extends Foo {
  public static final int[] $__my_field;

  public Foo$ExtendsFoo();
    Code:
       0: getstatic     #18                 // Field $__my_field:[I
       3: iconst_0      
       4: dup2          
       5: iaload        
       6: iconst_1      
       7: iadd          
       8: iastore       
       9: aload_0       
      10: invokespecial #1                  // Method Foo."<init>":()V
      13: getstatic     #18                 // Field $__my_field:[I
      16: iconst_1      
      17: dup2          
      18: iaload        
      19: iconst_1      
      20: iadd          
      21: iastore       
      22: return        
    LineNumberTable:
      line 12: 0
      line 13: 13

  static {};
    Code:
       0: iconst_2      
       1: newarray       int
       3: putstatic     #18                 // Field $__my_field:[I
       6: return        
}
```
and, when I run the test case (using for example JUnit command line) on the instrumented code, I got the following exception:
```
java.lang.ExceptionInInitializerError
	at TestFoo.test(TestFoo.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
        ...
Caused by: java.lang.NullPointerException
	at Foo$ExtendsFoo.<init>(Foo.java:12)
	at Foo.<clinit>(Foo.java:4)
```

it seems that the JVM tries to create a new instance of `Foo`, which creates a new instance of `ExtendsFoo` in the static constructor, and the exception occurs. if I don't instrument the constructor of `ExtendsFoo` class, the `java.lang.ExceptionInInitializerError` isn't thrown and the test case returns success.

am I doing something really wrong? or, is this a Javassist issue?

--
Thanks

**Comment by chibash** [comment]
I think the constructor of Foo$ExtendsFoo was called before Foo$ExtendsFoo.$__my_field is initialized
because it is initialised after Foo's static constructor finishes.  It makes a loop.

**Comment by jose** [comment]
thanks @chibash for your quick reply.
I guess the solution is to just use one instance of `$__my_field array`. I.e., rather than having two instance of `$__my_field` (one in `Foo`, and another in `Foo$ExtendsFoo` class), just having one declared in `Foo` class (but used on both classes) should solve the problem.

**Comment by chibash** [comment]
Yes, I think that's a good solution.

**Comment by jose** [comment]
and what if, instead of having

`public static final int[] $__my_field = new int[10]; // 10 is just an example`

initialized in the static constructor, having something like

`public static int[] $__my_field = null;`

and then, on every call to `$__my_field` I check whether it is null or not:

`if ($__my_field == null) { $__my_field = new int[10]; } $__my_field[1] += 1; ....`

question is, how to create a [javassist.bytecode.Bytecode](https://jboss-javassist.github.io/javassist/html/javassist/bytecode/Bytecode.html) object with that if condition?


--
Thanks
