### ISSUE TITLE
java.lang.ClassCastException: javassist.bytecode.NameAndTypeInfo cannot be cast to javassist.bytecode.ClassInfo

### ISSUE THREAD

**Issue by ravindraBoy** [jboss-javassist/javassist#77]
I guess there was a similar thread posted around 2 years ago. Happens when I am including the name of the class I am writing test case for in @PrepareForTest annotation. I am using javassist 3.20 jar. When I exclude the class name in the annotation, my mocked object isn't getting passed and the real constructor is being called instead.

**Comment by ravindraBoy** [comment]
It happens at line 242 in ConstPool class's getClassInfo method

**Comment by chibash** [comment]
Is this an issue of powermock?  It is a separate project and I guess this issue is not a bug of javassist.
Please talk to powermock developers.
