### ISSUE TITLE
Expose getItem(int n) in ConstPool

### ISSUE THREAD

**Issue by MylesIsCool** [jboss-javassist/javassist#81]
Hi there, first of all, thanks for making javassist it's amazing and definitely my favourite library.

Is there any chance of modifying the method ConstPool.getItem(int n) to be public?

(https://github.com/jboss-javassist/javassist/blob/master/src/main/javassist/bytecode/ConstPool.java#L218)

Why?

Currently there is no way to iterate through the items in a ConstPool, there's methods if you know the type such as getLdcValue, but a lot of the times you have to write hacky workarounds.

An example could be this project, 

https://bitbucket.org/cuchaz/enigma/src/6dfb5fc6325986b283fbdbbe7141ba8950811b46/src/cuchaz/enigma/bytecode/accessors/ConstInfoAccessor.java?at=default&fileviewer=file-view-default

Overall it would be nicer to expose the API with simple getters, do you have any opinion on this?

Thanks,

Myles

**Comment by chibash** [comment]
I understand your demand.  The reason is that ConstInfo and its subclasses are not public.
But ConstPool already has getTag(int).  So you can write as follows:
```
for (int i = 0; i < size; i++)
    if (constPool.getTag(i) == ConstPool.CONST_utf8) {
        String s = constPool.getUtf8Info(i);
        do something
    }
```
Doesn't this fit your use case?

**Comment by MylesIsCool** [comment]
@chibash 

Unsure why I overlooked this, but yeah that looks like it works for me. Thanks!
