### ISSUE TITLE
Mutual recursive methods doesn't work

### ISSUE THREAD

**Issue by avurro** [jboss-javassist/javassist#91]
Hi,

I followed the instructions in the documentation but I get the following error:
`conflict *top*`
My code is identical to that described, with some different names of course.
I do not know what else to try.

**Comment by chibash** [comment]
Which code did you run when you got that error?
Which compiler (javac or eclipse?) and which VM (JDK1.8?) did you use?

**Comment by avurro** [comment]
> My code is identical to that described, with some different names of course.

```java
CtClass cc = ... ;
CtMethod factoryMethod = CtNewMethod.make("public abstract DestinationFactory getFactory();", cc);
CtMethod mapping = CtNewMethod.make("public abstract Destination mapping();", cc);
cc.addMethod(factoryMethod);
cc.addMethod(mapping);
factoryMethod.setBody("{ return factory.make(); }");
mapping.setBody("{ return getFactory()!=null? null: getFactory(); }");
cc.setModifiers(cc.getModifiers() & ~Modifier.ABSTRACT);
```
With two differents:
cc implements an interface and getFactory call a field inside (factory).

I need time to create a test case, in the middle time if you have any idea will be welcomed.

**Comment by avurro** [comment]
this is the complete message:
`javassist.CannotCompileException: by javassist.bytecode.BadBytecode: nullVSouAllAll (Ljava/lang/Object;)Ljava/lang/Object; in comgooglecodejmapperintegrationtestothersgithubbeanNotEmptyConstructorcomgooglecodejmapperintegrationtestothersgithubbeanSimpleBean: conflict: *top* and com.googlecode.jmapper.integrationtest.others.github.bean.NotEmptyConstructor`

test is in progress.

**Comment by avurro** [comment]
after a some debug i have seen that the exeception is thrown by this line of code:
`methodInfo.rebuildStackMapIf6(cc.getClassPool(), cc.getClassFile2());`

this exception is thrown only when i try to set the method body that calls an instance field inside: `ctMethod.setBody(body)` where body contains a call to the instance field.

any suggestions?

**Comment by avurro** [comment]
this field is of interface type

**Comment by avurro** [comment]
fixed, thank you for your great help.

**Comment by chibash** [comment]
The test case did not reproduce a bug.
