### ISSUE TITLE
CtMethod hash and equals methods ignores class

### ISSUE THREAD

**Issue by 43k** [jboss-javassist/javassist#93]
Methods are seen as equal no matter what class they belong to.

CtMethod.hashCode() and CtMethod.equals(Object obj) both use getStringRep() which does not include the class.

**Comment by chibash** [comment]
That's the intended behaviour.  It's too late to change it due to backward compatibility.

**Comment by 43k** [comment]
Thanks for the reply.

Just curious, how can this be intended behavior?
Why would you want methods from completely different classes to be seen as the same method just because they happen to have the same name and argument types?

Regarding backward compatibility; how could a fix of this break someones code?
If someone is relying on this behavior, then I would say they have a serious issue with their design.

**Comment by chibash** [comment]
hashCode() and equals() were implemented as such to make it easy to find overridden methods (the same name and signature but different declaring classes).
I agree that that was not good design choice but happened more than a decade ago.
